### ISSUE TITLE
Small nitpick in very-tiny-diffusion.ipynb

### ISSUE THREAD

**Issue by louiserfallon** [andrewkchan/very-tiny-diffusion#1]
In your blog https://andrewkchan.dev/ & in the markdown above it, you say step 2 is using linear embeddings for time, but the code says fourier fourier (same as step 3)

**Comment by andrewkchan** [comment]
Thanks! That’s a mistake in the notebook.

**Comment by andrewkchan** [comment]
Fixed https://github.com/andrewkchan/very-tiny-diffusion/commit/0a7af21b9eaa832cad4849d7800506d8a7d8233d
